{{- if .Values.exampleSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exampleSecret.name }}
stringData:
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: {{ include "corvid.fullname" (dict
      "Chart" (dict "Name" "postgres")
      "Values" .Values.postgres.postgres
      "Release" .Release
  ) }}
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  DATA_ENCRYPTION_KEY: "2zfgzc82XbDJ2sRmQ6W48QtG2W6FvTPc" # must be 32 chars long, choose your own
  SESSION_SECRET: "dummySessionSecret" # bring your own
  JWT_SECRET: "dummyJwtSecret" # bring your own
  # WHITELISTED_ORIGINS: "http://localhost:3170,http://localhost:3000,http://localhost:3100,app://localhost_3200,app://hoppscotch"
  WHITELISTED_ORIGINS: "http://localhost:3170,http://localhost:3000,http://localhost:3100,app://localhost_3200,app://hoppscotch"

  # Base URLs
  VITE_BASE_URL: http://localhost:3000
  VITE_SHORTCODE_BASE_URL: http://localhost:3000
  VITE_ADMIN_URL: http://localhost:3100
  # Backend URLs
  VITE_BACKEND_GQL_URL: http://localhost:3170/graphql
  VITE_BACKEND_WS_URL: ws://localhost:3170/graphql
  VITE_BACKEND_API_URL: http://localhost:3170/v1
  # Terms of service and privacy policy links
  VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
  VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
  VITE_PROXYSCOTCH_ACCESS_TOKEN: ""
  # if you want to have a subdomain
  ENABLE_SUBPATH_BASED_ACCESS: "false"
{{- end }}
