{{- if .Values.exampleSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exampleSecret.name }}
stringData:
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: {{ include "corvid.fullname" (dict
      "Chart" (dict "Name" "postgres")
      "Values" .Values.postgres.postgres
      "Release" .Release
  ) }}
{{- end }}
