apiVersion: v2
appVersion: "2025.11.29" # renovate: datasource=docker depName=ghcr.io/alexta69/metube
description: A Helm chart for Kubernetes
name: metube
type: application
version: 0.4.0
dependencies:
- alias: metube
  name: corvid-app
  version: 0.17.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: metube.enabled
