apiVersion: v2
appVersion: "26.5.1" # renovate: datasource=docker depName=quay.io/keycloak/keycloak
description: A Helm chart for Kubernetes
name: keycloak
type: application
version: 0.5.0
dependencies:
- alias: keycloak
  name: corvid-app
  version: 0.13.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: keycloak.enabled
- name: postgres
  version: 0.2.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: postgres.enabled
