apiVersion: v2
appVersion: "2025.11.1" # renovate: datasource=docker depName=docker.io/cloudflare/cloudflared
description: A Helm chart for Kubernetes
name: cloudflared
type: application
version: 0.5.0
dependencies:
- name: corvid
  version: 0.12.0
  repository: "https://gitlab.com/api/v4/projects/55284972/packages/helm/stable"
