apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: hoppscotch
type: application
version: 0.1.0
dependencies:
- alias: frontend
  name: corvid-app
  version: 0.16.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: frontend.enabled
- alias: admin
  name: corvid-app
  version: 0.16.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: admin.enabled
- alias: backend
  name: corvid-app
  version: 0.16.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: backend.enabled
- alias: migrate
  name: corvid-app
  version: 0.16.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: migrate.enabled
- name: postgres
  version: 0.2.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: postgres.enabled
